=== hernandazevedo/aulas-monitoria-infnet-java/Mock/conf/configTestMock.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="qualified">
	
	<xs:complexType name="tAtributo">
		<!-- <xs:attribute name="metodo" type="xs:string" />  -->
		<xs:attribute name="valor" type="xs:string" use="optional" />
		<xs:attribute name="classe" type="xs:string" use="optional" />
		<xs:attribute name="metodo" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="tObjeto">
		<xs:sequence>
			<xs:element name="atributoSimples" type="tAtributo" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="atributoComplexo" type="tObjeto" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="classe" type="xs:string" />
		<xs:attribute name="metodo" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="tTestCase">
	 <xs:sequence>
		<xs:element name="atributoSimples" type="tAtributo" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="atributoComplexo" type="tObjeto" minOccurs="0"
				maxOccurs="unbounded" />
	</xs:sequence>
		<!-- <xs:sequence>
			<xs:element name="parametro" type="tObjeto" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="retorno" type="tObjeto" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
		 -->
		<xs:attribute name="name" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="tTest">
		<xs:sequence>
			<xs:element name="testCase" type="tTestCase" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="activeTestCaseName" type="xs:string" />
	</xs:complexType>

	<xs:element name="test" type="tTest" />
</xs:schema>

=== hernandazevedo/aulas-monitoria-infnet-java/Mock/conf/certificarOut.xml
<?xml version="1.0"?>
<test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="configTestMock.xsd" activeTestCaseName="Cenario 1">
	<!-- - certificação de TV - retornando tudo ok  -->
	
	<testCase name="Cenario 1">
		<atributoComplexo classe="com.pessoa.Pessoa">
			<atributoSimples valor="William Italiano" metodo="setNome" classe="java.lang.String"/>
			<atributoComplexo classe="com.pessoa.Pessoa" metodo="setPessoa">
			    <atributoSimples valor="jose" metodo="setNome" classe="java.lang.String" />			    
			</atributoComplexo>
			<atributoComplexo classe="com.pessoa.Pessoa[]" metodo="setListaDeContatos">
				<atributoComplexo classe="com.pessoa.Pessoa">
					<atributoSimples valor="William Italiano 1" metodo="setNome" classe="java.lang.String"/>
				</atributoComplexo>
				<atributoComplexo classe="com.pessoa.Pessoa">
					<atributoSimples valor="William Italiano 2" metodo="setNome" classe="java.lang.String"/>
				</atributoComplexo>
				<atributoComplexo classe="com.pessoa.Pessoa">
					<atributoSimples valor="William Italiano 3" metodo="setNome" classe="java.lang.String"/>
				</atributoComplexo>
				<atributoComplexo classe="com.pessoa.Pessoa">
					<atributoSimples valor="William Italiano 4" metodo="setNome" classe="java.lang.String"/>
				</atributoComplexo>				
			</atributoComplexo>		
		</atributoComplexo>
	</testCase>

</test>
